/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BASE_URL: typeof import('../lib/constants')['BASE_URL']
  const FetchProgressEvent: typeof import('../lib/fetch')['FetchProgressEvent']
  const cn: typeof import('../utils/cn')['cn']
  const createRef: typeof import('react')['createRef']
  const extractText: typeof import('../lib/extractText')['extractText']
  const extractTitle: typeof import('../lib/gemini')['extractTitle']
  const formatBearing: typeof import('../utils/index')['formatBearing']
  const formatFileSize: typeof import('../utils/index')['formatFileSize']
  const formatThousands: typeof import('../utils/index')['formatThousands']
  const forwardRef: typeof import('react')['forwardRef']
  const getStreamSize: typeof import('../lib/fetch')['getStreamSize']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const parseXMindFile: typeof import('../lib/xmind')['parseXMindFile']
  const startTransition: typeof import('react')['startTransition']
  const summaryContent: typeof import('../lib/gemini')['summaryContent']
  const trackRequestProgress: typeof import('../lib/fetch')['trackRequestProgress']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImageUpload: typeof import('../hooks/use-image-upload')['useImageUpload']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useMindMapNoteStore: typeof import('../store/mind-map-note')['useMindMapNoteStore']
  const useOutsideClick: typeof import('../hooks/useOutsideClick')['useOutsideClick']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
  const useUserStore: typeof import('../store/user')['useUserStore']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { User } from '../store/user'
  import('../store/user')
}
