/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AuthenticatedOnly: typeof import('../components/auth/owner-only')['AuthenticatedOnly']
  const BASE_URL: typeof import('../lib/constants')['BASE_URL']
  const Back: typeof import('../components/keep/back')['Back']
  const Badge: typeof import('../components/ui/badge')['Badge']
  const Base64Converter: typeof import('../components/image/base64-converter')['Base64Converter']
  const Button: typeof import('../components/ui/button')['Button']
  const Card: typeof import('../components/ui/card')['Card']
  const Confirm: typeof import('../components/ui/confirm')['Confirm']
  const CustomNoteContent: typeof import('../components/mindmap/CustomNoteContent')['CustomNoteContent']
  const FetchProgressEvent: typeof import('../lib/fetch')['FetchProgressEvent']
  const ImageCard: typeof import('../components/image/image-card')['ImageCard']
  const ImageInfoModal: typeof import('../components/image/image-info-modal')['ImageInfoModal']
  const ImageList: typeof import('../components/image/list')['ImageList']
  const ImageUpload: typeof import('../components/image/upload')['ImageUpload']
  const KeepList: typeof import('../components/keep/list')['KeepList']
  const LoadingSpinner: typeof import('../components/ui/loading-spinner')['LoadingSpinner']
  const MdRender: typeof import('../components/md-render/index')['MdRender']
  const Modal: typeof import('../components/ui/modal')['Modal']
  const OwnerOnly: typeof import('../components/auth/owner-only')['OwnerOnly']
  const Pre: typeof import('../components/md-render/index')['Pre']
  const PrismCode: typeof import('../components/md-render/PrismCode')['PrismCode']
  const Switch: typeof import('../components/ui/switch')['Switch']
  const Textarea: typeof import('../components/ui/textarea')['Textarea']
  const UserProvider: typeof import('../components/auth/user-provider')['UserProvider']
  const cn: typeof import('../utils/cn')['cn']
  const createRef: typeof import('react')['createRef']
  const diffPage: typeof import('../components/diff/diff-page')['default']
  const extractText: typeof import('../lib/extractText')['extractText']
  const extractTitle: typeof import('../lib/gemini')['extractTitle']
  const formatBearing: typeof import('../utils/index')['formatBearing']
  const formatFileSize: typeof import('../utils/index')['formatFileSize']
  const formatThousands: typeof import('../utils/index')['formatThousands']
  const forwardRef: typeof import('react')['forwardRef']
  const getStreamSize: typeof import('../lib/fetch')['getStreamSize']
  const icon: typeof import('../components/user/icon')['default']
  const lazy: typeof import('react')['lazy']
  const loginButton: typeof import('../components/user/login-button')['default']
  const mdEditor: typeof import('../components/md-editor/index')['default']
  const memo: typeof import('react')['memo']
  const mindmap: typeof import('../components/mindmap/index')['default']
  const parseXMindFile: typeof import('../lib/xmind')['parseXMindFile']
  const startTransition: typeof import('react')['startTransition']
  const summaryContent: typeof import('../lib/gemini')['summaryContent']
  const trackRequestProgress: typeof import('../lib/fetch')['trackRequestProgress']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useMindMapNoteStore: typeof import('../store/mind-map-note')['useMindMapNoteStore']
  const useOutsideClick: typeof import('../hooks/useOutsideClick')['useOutsideClick']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
  const useUserStore: typeof import('../store/user')['useUserStore']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { User } from '../store/user'
  import('../store/user')
}
