name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/json4u.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  docker-build-and-push-arm:
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up QEMU for ARM support
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      # Set up Docker Buildx with a unique builder name
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api.us4ever:latest
          cache-from: |
            type=local,src=/home/runner/.buildx-cache
          cache-to: |
            type=local,dest=/home/runner/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /home/runner/.buildx-cache
          mv /home/runner/.buildx-cache-new /home/runner/.buildx-cache

      - name: Update container
        run: |
          cd /root/applications
          docker pull ${{ secrets.DOCKER_USERNAME }}/api.us4ever
          docker-compose up -d --force-recreate api.us4ever
          docker ps -a --filter "ancestor=${{ secrets.DOCKER_USERNAME }}/api.us4ever" -q | xargs docker rm -f
