name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/json4u.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

# 全局环境变量，多个 job 可以共享
env:
  SERVICE_NAME: us4ever.com
  DOCKER_REPOSITORY: powerfulyang/us4ever.com

jobs:
  docker-build-and-push-arm:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up QEMU for ARM support
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      # Set up Docker Buildx with a unique builder name
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ env.DOCKER_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: [docker-build-and-push-arm]
    runs-on: self-hosted
    steps:
      - name: Update container
        run: |
          cd /root/applications
          docker pull ${{ env.DOCKER_REPOSITORY }}
          docker-compose up -d --force-recreate ${{ env.SERVICE_NAME }}
          docker image prune -f
          docker-compose up -d
