name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/json4u.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  docker-build-and-push-arm:
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api.us4ever .

      - name: Update container
        run: |
          cd /root/applications
          docker-compose up -d --force-recreate api.us4ever
          docker image prune -f
          docker-compose up -d
